# Run: $uvicorn serve.fastapi_app_onnx:app --host 0.0.0.0 --port 8000
# Access in browser at: http://localhost:8000/docs

from fastapi import FastAPI
from pydantic import BaseModel

from optimum.onnxruntime import ORTModelForCausalLM
from transformers import AutoTokenizer

import time
import psutil
import os
from pathlib import Path

app = FastAPI()

# The ONNX [or other model] model should be loaded at startup — not inside the endpoint

model_load_start = time.perf_counter() 

model = ORTModelForCausalLM.from_pretrained("model_onnx")
tokenizer = AutoTokenizer.from_pretrained("model_onnx")
tokenizer.pad_token = tokenizer.eos_token

model_load_time = time.perf_counter() - model_load_start # <-- model startup metrics capture here

# Model file size in MB
model_file_size_mb = round(
    Path("model_onnx/model.onnx").stat().st_size / (1024 * 1024), 2
)

class GenerateRequest(BaseModel):  # use Pydantic model, not query params
    prompt: str
    max_new_tokens: int = 100

@app.post("/generate")
def generate(request: GenerateRequest):

    # System snapshot BEFORE. To get RAM before inference (MB)... could be overkill
    # Documenting in case I need this ina larger project
    process = psutil.Process(os.getpid())
    ram_before = process.memory_info().rss / (1024 * 1024)
    cpu_before = process.cpu_percent(interval=None) # This model uses CPU, so this makes more sense

    inputs = tokenizer(request.prompt, return_tensors="pt")
    input_tokens = inputs["input_ids"].shape[1]

    # ---> Inference starts here
    e2e_start = time.perf_counter()

    output = model.generate(
        **inputs, 
        # max_new_tokens=request.max_new_tokens
        max_length=request.max_new_tokens,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95,
        repetition_penalty=1.2,
        )

    e2e_latency = time.perf_counter() - e2e_start # seconds

    # System snapshot AFTE
    ram_after = process.memory_info().rss / (1024 * 1024) # ---> # RAM after inference (MB)
    cpu_after = process.cpu_percent(interval=None)  # % of one core

    output_tokens = output.shape[1] - input_tokens # New tokens generated by the model

    # Derived metrics
    tokens_per_second = round(output_tokens / e2e_latency, 2)
    tpot_ms = round((e2e_latency / output_tokens) * 1000, 2)  # average time per each output token - ms per token
    
    # time until first token appears ---> TTFT ≈ e2e_latency for non-streaming inference
    ttft_approx = round(e2e_latency, 4) # NOTE: True TTFT requires streaming — this is an approximation.
                                        #       In non-streaming inference the model generates all tokens 
                                        #       before returning anything. The formula for streaming is:
                                        #       TTFT = time_first_token_received - time_request_sent

    decoded = tokenizer.decode(output[0], skip_special_tokens=True)

    return {
        "text": decoded,

        # Toekn counts
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,

        # Latency
        "latency_sec": round(e2e_latency, 4), # seconds
        "ttft_approx_s": ttft_approx,         # seconds
        "tpot_msec": tpot_ms,                 # ---> how long does each word take to appear? [milliseconds per token]
        
        # Throughput
        "tokens_per_second": tokens_per_second, # ---> how fast is this system overall?

         # Efficiency
        "cpu_percent": round(cpu_after, 1),               # how hard the CPU worked during inference? - % of a single core
        "ram_used_mb": round(ram_after - ram_before, 2),  # memory consumed by THIS request - MB
        "peak_ram_mb": round(ram_after, 2),               # high water mark — tells you if you'll OOM at scale - MB
        "model_file_size_mb": model_file_size_mb,         # MB
        "model_load_time_s": round(model_load_time, 4),   # seconds
    }

@app.get("/health")
def health():
    return {"status": "ok"}